const users = [
  {
    id: 1,
    firstName: "Rahul",
    lastName: "Sharma",
    email: "rahul@gmail.com",
    age: 25,
    gender: "Male",
    phone: "9876543210",
    city: "Mumbai",
    country: "India",
    occupation: "Software Engineer",
    isActive: true
  },
  {
    id: 2,
    firstName: "Priya",
    lastName: "Patel",
    email: "priya@gmail.com",
    age: 28,
    gender: "Female",
    phone: "9123456780",
    city: "Ahmedabad",
    country: "India",
    occupation: "Designer",
    isActive: true
  },
  {
    id: 3,
    firstName: "Amit",
    lastName: "Verma",
    email: "amit@gmail.com",
    age: 32,
    gender: "Male",
    phone: "9988776655",
    city: "Delhi",
    country: "India",
    occupation: "Manager",
    isActive: false
  },
  {
    id: 4,
    firstName: "Sneha",
    lastName: "Iyer",
    email: "sneha@gmail.com",
    age: 24,
    gender: "Female",
    phone: "9000011111",
    city: "Chennai",
    country: "India",
    occupation: "Doctor",
    isActive: true
  },
  {
    id: 5,
    firstName: "Arjun",
    lastName: "Singh",
    email: "arjun@gmail.com",
    age: 29,
    gender: "Male",
    phone: "9111122222",
    city: "Jaipur",
    country: "India",
    occupation: "Entrepreneur",
    isActive: true
  },
  {
    id: 6,
    firstName: "Meera",
    lastName: "Reddy",
    email: "meera@gmail.com",
    age: 26,
    gender: "Female",
    phone: "9222233333",
    city: "Hyderabad",
    country: "India",
    occupation: "Teacher",
    isActive: false
  },
  {
    id: 7,
    firstName: "Karan",
    lastName: "Malhotra",
    email: "karan@gmail.com",
    age: 31,
    gender: "Male",
    phone: "9333344444",
    city: "Pune",
    country: "India",
    occupation: "Analyst",
    isActive: true
  },
  {
    id: 8,
    firstName: "Anjali",
    lastName: "Kapoor",
    email: "anjali@gmail.com",
    age: 27,
    gender: "Female",
    phone: "9444455555",
    city: "Bangalore",
    country: "India",
    occupation: "HR",
    isActive: true
  },
  {
    id: 9,
    firstName: "Vikram",
    lastName: "Joshi",
    email: "vikram@gmail.com",
    age: 35,
    gender: "Male",
    phone: "9555566666",
    city: "Kolkata",
    country: "India",
    occupation: "Consultant",
    isActive: false
  },
  {
    id: 10,
    firstName: "Riya",
    lastName: "Nair",
    email: "riya@gmail.com",
    age: 23,
    gender: "Female",
    phone: "9666677777",
    city: "Goa",
    country: "India",
    occupation: "Content Writer",
    isActive: true
  }
];

module.exports = users