name: Fullstack CI Pipeline - Piyush

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-piyush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code - Piyush
        uses: actions/checkout@v3

      - name: Setup Node - Piyush
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      # Backend
      - name: Install Backend Dependencies - Piyush
        run: |
          cd backend
          npm install

      - name: Run Backend Jest Tests - Piyush
        run: |
          cd backend
          npm test

      # Frontend
      - name: Install Frontend Dependencies - Piyush
        run: |
          cd frontend
          npm install

      - name: Run Frontend Unit Tests - Piyush
        run: |
          cd frontend
          npm test

      - name: Run Cypress Tests - Piyush
        run: |
          cd frontend
          npx cypress run
        env:
          CYPRESS_BASE_URL: https://fullstack-ci.vercel.app/

  deployment-piyush:
    runs-on: ubuntu-latest
    needs: test-piyush
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Install Frontend Dependencies - Piyush
        run: |
          cd frontend
          npm install

      - name: Build Frontend - Piyush
        run: |
          cd frontend
          npm run build

      - name: Deploy to Vercel - Piyush
        run: |
          cd frontend
          npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}